# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f1d896a7e35a0441a87f8a25f03a7385011efec35971a4337e34b67d3978f67d80c4a2efb8e33207c72063c0ef5827a3b3b5be5f20f6d4b3154fea4e9e0a9bd

test:
  secret_key_base: 1bd4c436675b5bcc05bca9dfdbd539b42a747ac3881253ee3400388578fd08d197e4ec3b410596d82c9ffd742fe51842c123cdde79abe6658dfe0aeee2e8afe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= APP_ENV['production']['secret_key_base'] %>
